version: "3.8"

services:
  app:
    build: .
    init: true
    environment:
      CONFIG_PATH: /data/config.json
      CHECKED_DATA_PATH: /data/checked/
    volumes:
      - type: bind
        source: data/
        target: /data/
